<a href="https://colab.research.google.com/github/Anasurya-Reddy/Basic_Machine_Learning/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1. Perform arithmetic operations on NumPy arrays.


In [ ]:
a =np.array([1,2,3])
b =np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


2. Write a script to compute the mean and standard deviation of a NumPy array.


In [ ]:
print(np.mean(a))
print(np.std(a))

2.0
0.816496580927726


3. Create a NumPy array of integers from 10 to 50 with a step size of 5.


In [ ]:
s = np.linspace(10,50,5)
print(s)

[10. 20. 30. 40. 50.]


4. Reshape the array into a 2x4 matrix.


5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.
• Replace all elements greater than 4 with 0.


6. Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division.


7. Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements.


8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.


9. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1.


10. Work with broadcasting and advanced operations in NumPy.
 Create a NumPy array arr of shape (3, 3) with random integers between
 1 and 20. Perform the following:
• Subtract the mean of each row from its respective elements (row-wise
normalization).
• Create a new array by squaring all the elements in arr.
• Find the indices of the top 3 maximum values in the entire array.