<a href="https://colab.research.google.com/github/Anasurya-Reddy/Basic_Machine_Learning/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Assignment-1***

In [ ]:
import numpy as np

1. Perform arithmetic operations on NumPy arrays.


In [43]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(f'Sum = {np.add(a,b)}')
print(f'Difference = {np.subtract(a,b)}')
print(f'Product = {np.multiply(a,b)}')
print(f'Division = {np.divide(a,b)}')
print(f'Power = {np.power(a,b)}')
print(f'Mod = {np.mod(a,b)}')

Sum = [5 7 9]
Difference = [-3 -3 -3]
Product = [ 4 10 18]
Division = [0.25 0.4  0.5 ]
Power = [  1  32 729]
Mod = [1 2 3]


2. Write a script to compute the mean and standard deviation of a NumPy array.


In [44]:
a = np.array([1,2,3])
print(f'Mean = {np.mean(a)}')
print(f'Standard Deviation = {np.std(a)}')

Mean = 2.0
Standard Deviation = 0.816496580927726


3. Create a NumPy array of integers from 10 to 50 with a step size of 5.


In [46]:
s = np.array(range(10,50,5))
print(f'Array = {s}')

Array = [10 15 20 25 30 35 40 45]


4. Reshape the array into a 2x4 matrix.


In [45]:
print(f'Reshaped Array = {s.reshape(2,4)}')

Reshaped Array = [[10 15 20 25]
 [30 35 40 45]]


5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.
• Replace all elements greater than 4 with 0.


In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Sub matrix = {arr[1:,:2]}')
arr[arr>4]=0
print(f'Modified Array = {arr}')

Sub matrix = [[4 5]
 [7 8]]
Modified Array = [[1 2 3]
 [4 0 0]
 [0 0 0]]


6. Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division.


In [48]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(f'Additon = {a+b}')
print(f'Multiplication = {a*b}')
print(f'Division = {a/b}')

Additon = [5 7 9]
Multiplicatio = [ 4 10 18]
Division = [0.25 0.4  0.5 ]


7. Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements.


In [50]:
a = np.random.rand(4,4)
print(f'Mean of Column = {np.mean(a,axis=0)}')
print(f'Max value = {np.max(a)}')
print(f'Sum = {np.sum(a)}')

Mean of Column = [0.57960697 0.49414723 0.42493456 0.48390349]
Max value = 0.94837862968959
Sum = 7.930368971995566


8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.


In [51]:
arr = np.array([1, 2, 3, 4])
print(f'Modified Arr = {2*(arr+10)}')

Modified Arr = [22 24 26 28]


9. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1.


In [52]:
arr = np.random.randint(1,100,(3,4,5))
print(f'Second 2D Arr = {arr[1]}')
print(f'Sub Arr = {arr[0,:2,-3:]}')
arr[arr%3==0]=-1
print(f'Modified Arr = {arr}')

Second 2D Arr = [[96 48 66 94 57]
 [61 89 69  5 41]
 [60 67  8 20  4]
 [38 34 22 75 77]]
Sub Arr = [[21 60 45]
 [45 71 80]]
Modified Arr = [[[44 53 -1 -1 -1]
  [14 68 -1 71 80]
  [49 91 49 16 50]
  [ 7 80 70 -1  7]]

 [[-1 -1 -1 94 -1]
  [61 89 -1  5 41]
  [-1 67  8 20  4]
  [38 34 22 -1 77]]

 [[-1 37 56 34 -1]
  [94 -1 49 70 -1]
  [73 46 91 37 92]
  [-1 77 85 85 37]]]


10. Work with broadcasting and advanced operations in NumPy.
 Create a NumPy array arr of shape (3, 3) with random integers between
 1 and 20. Perform the following:
• Subtract the mean of each row from its respective elements (row-wise
normalization).
• Create a new array by squaring all the elements in arr.
• Find the indices of the top 3 maximum values in the entire array.

In [55]:
arr = np.random.randint(1,20,(3,3))
print(f'Normalized Arr = {arr-np.mean(arr,axis=1,keepdims=True)}')
sqa = np.square(arr)
print(f'Square Arr = {sqa}')
print(f'Max Indices = {np.argsort(arr.flatten())[-3:]}')

Normalized Arr = [[  5.66666667  -6.33333333   0.66666667]
 [-10.33333333   5.66666667   4.66666667]
 [ -2.           2.           0.        ]]
Square Arr = [[196   4  81]
 [  4 324 289]
 [196 324 256]]
Max Indices = [5 4 7]
